In [3]:
## Importing Libraries
import requests
from bs4 import BeautifulSoup
import pandas as pd
import numpy as np
import re

In [15]:
## Question :- From the URL:'https://books.toscrape.com/', use web-scrapping and store the Title, Link, Price, Quantity of books
## Csv file.

In [16]:
## Ans:-

In [12]:
base_url = 'https://books.toscrape.com/catalogue/'
current_page = 'http://books.toscrape.com/catalogue/page-1.html'

response = requests.get(current_page)
book_details = []
while response.status_code == 200:
    
    data = BeautifulSoup(response.text,'html.parser')
    books = data.find_all(class_='product_pod')
    
    for book in books:
        url = base_url + book.h3.a['href']
        res = requests.get(url)
        data1 = BeautifulSoup(res.text,'html.parser')
        
        title = data1.h1.string.strip()
        price = data1.find(class_='price_color').string
        qty = data1.find(class_='instock availability')
        qty = qty.contents[-1].strip()
        qty = int(re.search('\d+',qty).group())
        price = float(re.search('[\d.]+',price).group())
        
        book_details.append([title,url,price,qty])
        
    next_page = data.find(class_='next')
    if next_page is None:
        break
    next_page_url = base_url + next_page.a['href']
    
    current_page = next_page_url
    response = requests.get(current_page)

In [13]:
df = pd.DataFrame(book_details, columns = ['Title','Link','Price','Quantity in Stock'])
df.to_csv('books.csv',index=False)

In [14]:
df

,Title,Link,Price,Quantity in Stock
0,A Light in the Attic,https://books.toscrape.com/catalogue/a-light-i...,51.77,22
1,Tipping the Velvet,https://books.toscrape.com/catalogue/tipping-t...,53.74,20
2,Soumission,https://books.toscrape.com/catalogue/soumissio...,50.10,20
3,Sharp Objects,https://books.toscrape.com/catalogue/sharp-obj...,47.82,20
4,Sapiens: A Brief History of Humankind,https://books.toscrape.com/catalogue/sapiens-a...,54.23,20
...,...,...,...,...
995,Alice in Wonderland (Alice's Adventures in Won...,https://books.toscrape.com/catalogue/alice-in-...,55.53,1
996,"Ajin: Demi-Human, Volume 1 (Ajin: Demi-Human #1)",https://books.toscrape.com/catalogue/ajin-demi...,57.06,1
997,A Spy's Devotion (The Regency Spies of London #1),https://books.toscrape.com/catalogue/a-spys-de...,16.97,1
998,1st to Die (Women's Murder Club #1),https://books.toscrape.com/catalogue/1st-to-di...,53.98,1
999,"1,000 Places to See Before You Die",https://books.toscrape.com/catalogue/1000-plac...,26.08,1